version: "3"

services:
  application:
    image: m1ster/ssbu-scoreboard-api
    ports:
      - "4000:4000"
    links:
      - mongo
    networks:
      - api
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - api
networks:
  api:
    driver: "bridge"
